name: iOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: actions/setup-xcode@v2
      with:
        xcode-version: '13.2' # Specify the desired Xcode version

    - name: Build
      run: |
        xcodebuild clean build \
          -workspace Morse.xcworkspace \
          -scheme Morse \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
          ONLY_ACTIVE_ARCH=NO

    - name: Run tests
      run: |
        xcodebuild test \
          -workspace Morse.xcworkspace \
          -scheme Morse \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
          ONLY_ACTIVE_ARCH=NO

    - name: Archive artifacts
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: XcodeLogs
        path: ~/Library/Developer/Xcode/DerivedData/**/*.xcresult
